### PR TITLE
Parse and compare versions of exiftool

### PR DESCRIPTION
**Pull request by jangop**
We should not compare versions as floats. Instead, we use `packaging.version.parse`:
```
required_version = version.parse("8.40")
actual_version = version.parse(str(actual["ExifTool:ExifToolVersion"]))
self.assertGreaterEqual(actual_version, required_version)
```

### CODE REVIEW

**Comment by sylikc** [comment]
Hey @jangop thanks for committing this, I'm reviewing the changes.  I've been a bit busy with life but wanted to get back to this, at least send the Python3 refactor out sometime hopefully early this year.

Are you actively using the Python3 version?  I have doubts anyone is, except me... I made quite a few code-breaking changes, particularly https://github.com/sylikc/pyexiftool/commit/15792bd6dbbc9ec435ab4446cc4bc95a6e12644a .

I just need to roll in your tests PR and I guess... just push it out and hope I don't get major backlash? 🤞

**Comment by sylikc** [comment]
Oh yeah, as per this issue, I also realized that there is a minimum version of Exiftool that is needed to get some of the stderr stuff working.  The ```-echo4``` parameter isn't supported in earlier versions of Exiftool https://github.com/sylikc/pyexiftool/blob/v0.5.x-py3-refactor/exiftool/exiftool.py#L753 ... so I actually do have to have a version check (I only found this out on an older version of Linux Mint exiftool)

**Comment by jangop** [comment]
I tend to stick to what's on pypi to make automated testing more convenient.

Your consideration is applaudable, but I believe that you can simply bump the version (see https://semver.org/) and not worry. That's what versions are for, after all. ☺️ And in projects where it matters, tests should be in place to catch potential issues.

**Comment by sylikc** [comment]
Oh wait, packaging is a PyPI.  Is there a Python-only equivalent without dependency?  I see the distutils is being deprecated.  https://stackoverflow.com/questions/11887762/how-do-i-compare-version-numbers-in-python

I ask because I found the version of Exiftool that is required by the Python3 refactor... 
[Exiftool older version history](https://exiftool.org/ancient_history.html)
* Jan. 18, 2021 - Version 12.15 (production release)
  * Fixed extra newline in -echo3 and -echo4 outputs added in version 12.10
* Nov. 12, 2020 - Version 12.10
  * Enhanced -echo3 and -echo4 options to allow exit status to be returned
  * Changed -execute so the -q option no longer suppresses the "{ready}" message when a synchronization number is used (eg. -execute123)

So I probably have to check v12.15 in exiftool startup, probably after running the ```-ver```... and need a version >= 12.15

**Comment by jangop** [comment]
This is merely for testing, right? Is pypi an issue?

**Comment by sylikc** [comment]
> This is merely for testing, right? Is pypi an issue?

Your PR is for testing only.  I actually need to implement something in Exiftool() class to check the exiftool version.  I'm planning to just use version_tuple property https://github.com/sylikc/pyexiftool/blob/v0.5.x-py3-refactor/exiftool/exiftool.py#L484 and do my own comparison... 

The current v0.5.x needs Exiftool 12.10 and above to even work because of the https://github.com/sylikc/pyexiftool/blob/v0.5.x-py3-refactor/exiftool/exiftool.py#L770 return status code parameter, which was apparently added after that version

**Comment by jangop** [comment]
Ah, alright. It does make sense to probe Exiftool's version whenever it's used. 👍

Using `packaging` or writing your own function both seem fine. ☺️ The latter should get its own tests, though.

**Comment by sylikc** [comment]
@jangop I see the change from tabs to spaces... but other than that, and a few comment styling changes, why was the ```test_set_list_keywords()``` removed?

**Comment by jangop** [comment]
> @jangop I see the change from tabs to spaces... but other than that, and a few comment styling changes, why was the `test_set_list_keywords()` removed?

Ah, yes, the actual changes are barely visible. They are in `test_get_metadata`.

I believe `test_set_list_keywords` was entirely commented out, was it not?

**Comment by sylikc** [comment]
well haha.  Yeah I guess commenting blocks out like that isn't good style... won't past lint?

Anyways, yeah I'm just merging a bunch of stuff, I just want to push out Python3 version lol... then deal with feedback from there :D

The encoding fixes, using string instead of bytes, etc etc... is like really really cool

**Comment by sylikc** [comment]
btw, what editor are you using?  I'm assuming removing all those comments to make the code more readable isn't helpful to you as your IDE might be doing something ... 

I am in Notepad++ so it's essentially a glorified plain text editor ... without the comment dividers and lots of functions the code gets hard to read really fast.

**Comment by jangop** [comment]
Commented blocks out are just, you know, potentially very confusing. ☺️ Everything is versioned anyhow, so one might as well delete a block that's not supposed to be there. And if there is an issue -- that's what [Issues](https://github.com/sylikc/pyexiftool/issues) are for. 😅 That way, it's easier to collaborate.

Nowadays I use PyCharm. At a certain point, I count no longer justify doing everything in gedit.

**Pull request merged**
