### PR TITLE
Test automatically

### PR DESCRIPTION
**Pull request by jangop**

### CODE REVIEW

**Comment by sylikc** [comment]
can I re-target this into the v0.5.x branch?  lol... I really will move off of that older branch... now with the encoding= fix

**Comment by sylikc** [comment]
I have a question, how do I test github actions without pushing new changes to the public repo every time?

And how do I debug them.  I Googled and the closest I got was https://stackoverflow.com/questions/59241249/how-to-run-github-actions-workflows-locally ... is that the way to develop these actions without having to commit and push every time I wanted to test?

**Comment by jangop** [comment]
Personally, I have given up and push-to-test. If I really feel out of my depths I'll create (maybe fork) a temporary repository where I can mess around as much as I want.

Maybe in the future things will change with regards to CI on github/gitlab. For now, you could take a look at https://github.com/firecow/gitlab-ci-local but I wouldn't sink too much time into this.

**Comment by jangop** [comment]
@sylikc Is there anything standing in the way of merging this?

**Comment by sylikc** [comment]
@jangop I'm still wary about the testing, although I guess best I just merge it rather than wait till I've read through and studied it.

I was looking at it earlier today and noticed it will commit to the ```master``` branch and not the re-factor.  So I guess it might be safe to do lol... since I only work on the refactor branch

**Comment by jangop** [comment]
I just find it super difficult to contribute without CI. 🤷

**Pull request merged**
